---
title: "[급류] Book Review - Approaches to Trauma & Loss" 
description: "Reviewing different approaches to trauma & loss in 급류 and Manchester by the Sea" 
date: "2026-04-10" 
toc: false
categories:
  - Reviews
---

## 트라우마와 상실에 대한 상등-상이한 접근, [급류]와 [Manchester by the Sea]

최근 정대건 작가의 [급류]라는 작품을 읽을 기회가 있었다. 이 책을 펼치고 1장을 마칠 때쯤, 굉장히 익숙한 작품이 동시에 머릿속에 떠올랐다. 개인적으로 굉장히 인상적으로 봤던 [Manchester by the Sea]라는 영화이다. 급류와 MS는 의도치 않은 실수로 인한 비극, 그리고 그로 인한 트라우마와 Grief를 안고 살아가는 화자들을 주요 제재로 사용한다는 점에서 굉장히 유사하다고 느껴진다. 하지만 서로 다른 표현 매체를 사용함에 따라 파생되는 전개와 표현 방식의 차이, 문화적/사회적 배경의 차이로 인한 작 내 분위기의 차이 역시 존재하기에 이 두 개의 작품을 비교하는 것은 굉장히 재미있다.

급류는 '진평'이라는 시골 지역에서의 *두 소년 소녀의 만남*이라는 모티프의 전형을 변주해, 부모의 죽음이라는 비극을 마주하는 상황을 연출한다. 서로를 사랑하는 두 아이들의 행동이 의도치 않은 불행을 불러오고 이로 인해 진평, 그리고 서로를 떠나게 된다. 하지만 시간이 지남에 따라 두 명은 서울이라는 한국 고유의 집합소에서 재회하게 되고, 이야기는 여기서 다시 이어지게 된다. MS는 'Manchester'이라는 해변 마을에서 Lee와 그의 가족에게 발생하는 비극을 조명한다. 분명 그의 실수는 맞지만, 그 누구도 탓할 수 없는 작은 방심으로 인한 거대한 비극으로 괴로워하는 모습은 스크린 밖에서 지켜보는 관객의 마음을 미어지게 만든다.

무엇보다 이 두 개의 작품이 다루는 주제는 잔인할 정도로 비극적이면서 매혹적이다. 사회적 동물인 인간이 살아가면서 마주할 수 있는 가장 참담한 비극은 무엇일까? 이 두 작품은 *'사랑하는 사람의 죽음에 나의 애매한 귀책이 있다는 점'*이라고 제시한다. 내가 생각하기에 작중 화자들이 느끼는 비통의 핵심은 바로 그 '애매함'에 있다. 사람이 하는 일에 인과관계가 분명하고, 잘잘못을 명확하게 나눌 수 있는 비중이 얼마나 될까? 급류에서 해솔이 후레쉬를 비춘 것과 Lee가 벽난로의 방화망을 치지 않은 것, 이를 독립적으로 놓고 보았을 때, 이를 명백한 살인 행위라고 정의할 수는 없을 것이다. 하지만 그것이 연쇄적인 역학관계를 촉발해 하나의 거대한 비극을 초래한 것 역시 진실이다. 그렇기에 그들은 주변으로부터 원치않는 용서를 강요받고, 그 속에서 그들은 오히려 스스로를 탓하고 파괴하게 되는 것이다. Lee가 경찰서에서 조사를 받은 뒤 집으로 돌아가도 좋다는 답변을 들었을 때, 총을 뽑아들어 자살을 시도하는 장면이 이 복잡한 내면을 정말 잘 표현했다고 생각한다.

## 사람은 견딜 수 없는 슬픔을 마주했을 때, 도망친다.

#### 장소

해솔과 도담, 그리고 Lee는 비극을 마주한 이후, 가장 먼저 '장소'를 옮기게 된다. 이들에게 있어 진평/Manchester는 빛나는 청춘의 장에서 빠르게 비극의 발원지, 가라앉는 우울한 장소로 변한다. 견딜 수 없는 슬픔을 마주 할 때 등장인물들은 그 장소에서 떠나는 것을 선택한다. 이들의 폐쇄적인 고향에서 만나는 모든 사람과 공간이 트라우마로 변했기 때문이다. 
그렇기에 그들은 자기혐오와 연민의 끝나지 않는 굴레에서 도피하기 위해 서울, Boston과 같은 '익명성'을 가질 수 있는 공간으로 떠난다. 수많은 사람이 스쳐지나가는 대도시 속에서 그들은 행인 A, 누군가의 이웃이라는 일반인의 연기를 하며 트라우마와 상실의 아픔으로부터 거리를 둘 기회를 얻는다.

#### 시간

마찬가지로 또 하나의 기제는 시간이다. 시간이 약이라는 말이 있듯이, 작중 시간의 흐름은 등장인물들의 트라우마 위에 이불을 덮어주는 역할을 한다. 이들은 더 이상 상실의 기억으로 매일 고통받지는 않는다. 하지만 그것은 결코 트라우마와 상실의 극복을 의미하지 않는다. 오히려 이들의 병리적 행동양식과 성격은 그 이면의 아픔에서 비롯되어 발달하게 된다. Lee가 단순한 아파트 관리인으로 살아가는 것과 도담이 술과 담배를 일삼는 것, 그리고 해솔이 극단적으로 성실한 생활을 하는 것은 다양한 자기파괴적 행위의 변주된 표현이라고 해석할 수 있다. 

## 트라우마와 상실은 극복함으로써 성장할 수 있다 - 급류의 동화적 해석

::: {.text-center}
***"두 사람 앞에 파도가 일고 있었지만 그들은 수영하는 법을 알았다."***
:::

이런 형벌을 수행하는 이들이 트라우마와 상실을 어떻게 마주하는지에 대해, 이 두 작품은 유사한 출발점에서 시작해 서로 다른 메시지를 전달한다. 

급류는 소설책이라는 매체를 활용했기 때문일까, 트라우마의 극복과 성장에 대한 동화적 결말을 제공한다. 해솔과 도담은 여러 풍파를 거쳐가면서도 의도와 우연에 힘입어 만남을 이어나가게 된다. 자기파괴적인 행위를 일삼고 트라우마로부터 회피하고자 하는 도담을 변화시키는 것은 해솔의 행보에서 출발한다. 놀랍게도 해솔은 도담의 아버지와 같은 소방관이 된다. 이어지는 해솔의 사고는 다시금 재회의 계기가, 더 나아가 트라우마를 정면으로 마주하는 기회가 된다. 

도담과 해솔은 진평으로 상징되는 과거의 상처에서 도망을 쳐왔지만, 종장에서는 진평을 방문하면서 그 기억과 그 기억을 담고 있는 상대를 제대로 마주하는 결정을 한다. 이렇게 그들은 급류 속에서 '수영'하는 법을 배우게 된 것이다. 다소 급박하게 진행되는 이야기는 아쉬움으로 남지만, 결국 급류의 이야기는 도담과 해솔의 능동적인 극복 서사로 끝맺는다.

## 어떤 상처들은 영원히 잊혀지지 않는다, 하지만 그럼에도 괜찮다 - MS의 현실적 해석

::: {.text-center}
***"Come on Patrick... I can't beat it. I'm sorry."***
:::

MS의 결말은 다소 다른 온도감을 가져간다. 물론, MS에서 트라우마의 극복과 해소를 부정하는 것은 결코 아니다. Patrick과 나누는 교감과 형의 유산인 배를 처분하지 않는 결정, 전처와 대면하며 나누는 대화 등은 Lee가 자신의 트라우마를 마주하고 해소하는 모습을 강렬하게 보여준다. 다만 MS는 급류와 같은 동화적인 결말과는 굉장히 다른, 보다 현실적인 해소의 모습에 보다 초점을 둔다. 

Lee는 과거의 사건 이후, 형의 죽음과 Patrick의 입양이라는 강제성을 가진 사건으로 인해 Manchester로 돌아오게 된다. 이혼한 전처와의 대면, Patrick과 보내는 시간, 그리고 수많은 이웃들과의 다툼은 Lee를 치유하기도 하지만, 그를 더욱 고통스럽게 하는 면이 명백히 커보인다. Lee가 Manchester에서 보내는 매 순간은 고통스러워 보이고, 떠나고 싶어 안달난 모습이 외적으로도 드러난다. 결국 Lee는 Manchester를 떠나 Patrick을 입양하는 것을 포기하고, 대신 그를 보러올 수 있는 근처의 도시로 이전한다. 마지막 장면의 "I can't beat it"은 Manchester에서 남은 그의 상처가 결코 완전히 치유될 수 없음을, 그리고 'it'이라고 밖에는 표현할 수 없을 정도로 아직까지도 쓰라리게 아프다는 것을 함축적으로 표현한다.

## 마무리

과거의 기억은 결코 쉽사리 잊혀지지 않고, 잊었다 생각한 감정들은 사소한 계기로도 일순간에 생명을 얻는다고 생각한다. 급류와 MS에서 공통적으로 강조하는 것이 있다면 트라우마는 완전히 없어질 수는 없는 것이라는 점이다. 그렇기에 중요한 것은 잊는 것보다도 *잊혀지지 않음에도 괜찮다는 것을 깨닫는 것*이라고 생각한다. 도담과 해솔처럼 전면적인 대면을 통해 이를 깨달을 수 있는 것이고, 반면 Lee와 같은 방법으로 자신의 트라우마와 make peace하는 방법도 존재하는 것이다. 세상을 살아가면서 누구나 자신만의 크고 작은 트라우마가 존재한다. 이런 작품들을 통해 한 번쯤, 자신의 방식대로 스스로의 내면을 돌아볼 수 있다면 한 층 더 단단해질 수 있는 계기가 될 수 있을 것이라 생각한다.