---
title: "[괴테는 모든 것을 말했다] Book Review - 자신의 언어로 담았을 때의 마법" 
description: "Reviewing Goethe said Everything" 
date: "2026-06-07" 
toc: false
categories:
  - Reviews
---

책을 덮자마자, 바로 처음부터 다시 읽고 싶다는 생각이 드는 책은 올해 들어 처음이었다. 이 책은 ‘문학 오타쿠가 정교하게 짜놓은 퍼즐’이라고 표현하는 것이 가장 적합할 것 같다. 실제로 이 책의 저자인 스즈키 유이는 01년생 작가임에도 이 하나의 책에서만 엿보이는 문학적 깊이는 경이롭다. 직전에 리뷰 모음에서 다뤘던 ‘최선의 삶’에서처럼, 신예 작가들의 장점은 색다른 소재의 발굴 또는 재해석, 그리고 그것을 활용한 흡입력 있는 전개에 머무는 경우가 많다(물론, 그것이 신예 작가의 작품을 읽는 이유이기도, 매력이기도 하다). 전체 작품의 짜임새나 마무리에서는 도리어 미흡한 모습을 보여 아쉬움을, 혹은 성장의 여지를 남기는 것이 일반적이다.

스즈키 유이의 『괴테는 모든 것을 말했다』는 놀랍게도 정반대의 노선을 탄다. 내가 이 소설을 칼로 잘라내야 한다면 전반부와 후반부를 80 : 20으로 자를 것이다. 나는 80%에 해당하는 전반부를 읽으면서 저자가 심어놓은 수많은 인용과 비유, 그리고 작품의 핵심 제재인 ‘괴테의 명언’에 대한 수수께끼 같은 이야기들을 헤맸다. 부끄럽지만 솔직히 말하자면, “쓸데없이 복잡하고 의미 불명의 인용이 많다”라는 생각이 들기도 했다. ‘독일 문학에 대해 아는 것은 아득히 예전에 읽었던 『파우스트』 정도였던 내가 볼테르, 루소, 프로스트 등의 작품과 명언에 대한 작중 화자들의 이야기를 들으며 무엇을 느껴야 하는 것일까?’ 하지만 이러한 인용투성이의 전개, 복잡한 문학사 이야기 등 역시 저자의 치밀한 의도로 이루어졌다는 것을 깨닫는 데는 오래 걸리지 않았다.

이 작품의 마법은 이야기를 마무리 짓는 마지막 20%에 있다. 정말 빠르면서도 정교한 방식으로 이전부터 뿌려두었던 암시들과 메시지를 총정리하면서, 작품을 ‘괴테의 명언 탐방기’에서 ‘이미 말해진 것들을 자신의 언어로 담는 것’이라는 관통하는 주제로 정렬시킨다. 책을 덮으면서 그동안 어렵게 읽어온 책의 모든 부분이 명료해지는 느낌이 들었고, 다시 읽었을 때 분명히 다르게 보이는 부분들이 있을 것이라는 확신이 들었다. 분명히 이 책은 다회독했을 때 더 빛나는 책일 것이다.

