---
title: "상반기 Book Review 모음" 
description: "Aggregate of Book Reviews I have read from 26 jan ~ may" 
date: "2026-05-31" 
toc: false
categories:
  - Reviews
---

**[M&A 거래와 PMI전략]**

M&A 부터 PMI 단계까지 폭넓게 다루어, 전체 프로세스를 훑기에 좋다. 단, 뎁스가 부족하다고 느껴지는 부분들이 많다.

**[M&A 거래의 기술]**

'M&A 거래와 PMI전략'과 유사하나, M&A에 집중한다. 위의 책보다 구체적인, 디테일 중심의 설명으로 진행되어, 함께 읽는 것이 도움이 된다.

**[사랑의 기술]**

사람은 누구나 연결되고 싶은 근본적 욕망이 존재하며, 그렇기에 필연적으로 사랑을 갈망한다. 하지만 사랑은 받고자하는 것보다, 주고자하는 것에서 시작해야한다. 읽을 땐 이해가 되면서도 실재와 연결하는건 또 다른 문제같다. 작가가 말하는 것처럼, 실행의 어려움이 존재한다는 것을 체감한다. 한번 더 읽어볼 필요가 있다.

**[급류]**

필력이 좋고, 독자의 흥미를 잘 이어가는 것이 느껴진다. 트라우마를 다룬 성장 소설이기에 내 취향에도 맞았다고 느꼈다. 단, 후반부의 전개와 마무리가 지나치게 속도가 빨라 어설프다고 느껴진 부분도 있다. 또한, 지나치게 희망적으로 진행되는 부분들이 존재해 몰입이 깨질 수도 있다고 느꼈다. 'Manchester by the Sea'와 함께 감상하면 더 좋을 것. 상세는 다음 포스팅으로 갈음한다. https://jesuspen-blog.github.io/posts/[%EC%8B%AF%EB%8B%A4%EB%A5%B4%ED%83%80]%20Book%20Review%20-%20Hermann%20Hesse's%20view%20of%20life/

**[브람스를 좋아하세요...]**

1959년작이라고 믿기 힘들 정도로 현대의 로맨스 소설과 견줄 수 있을 정도의 생동감을 지니고 있다. 당시 시대에서 '브람스'라는 음악가가 가지는 특유의 포지션을 이해한다면 더 이해하기 쉬울 것이다. 일탈적 사랑의 뜨거운 매력과 동시에 결국 변하지 못하는 사람들의 본질을 보며 남기는 씁슬한 마무리가 인상적이다.

**[인간 실격]**

다자이 오사무의 인간 실격이 특히 유명했던 이유는 당시의 시대상과 결부된 것이라고 생각된다. 개인적으로는 이를 배제하고 읽어, 이 책의 완전한 가치를 이해하지는 못했다고 생각한다. 

나는 자신의 중심을 잡지 못하고 사람의 눈치만을 보며 살아가는 요조의 모습에 몰입했다. 정신적으로 성숙하지 못했던 나의 과거와도 많은 부분 겹쳐있다고 느낀 탓이다. 타인의 시선에 지나치게 신경쓰다못해 억측까지 이어지는 병리적 모습은 자신의 중심을 잡지 못했던 나를 포함한 많은 사람들의 모습이기도 할 것이다. 자신과의 대화를 통해 스스로를 이해하고, 이를 케어해나가며 단단하게 살아가는 것은 모든 사람의 영원한 숙제일 것이다.

**[싯다르타]**

헤르만 헤세 작품답게 인생에 대한 존재론적 고찰을 담고 있는 만큼, 한문장씩 충분히 읽어나가는데 시간이 많이 필요했다. 강에 비유되는 삶을 하나의 거대한 흐름으로서 받아들이고, 긍정하는 자세를 지닌다면 행복할 수 있을 것이다. 상세는 다음 포스팅으로 갈음한다. https://jesuspen-blog.github.io/posts/[%EA%B8%89%EB%A5%98]%20Book%20Review%20-%20Approaches%20to%20Trauma%20&%20Loss/

**[최선의 삶]**

작가가 살아온 삶의 생채기가 실감나게 느껴져, 몰입을 놓지 않고 읽어낼 수 있었다. 작품의 소재자체는 특별하지 않은 성장소설이지만, 그 묘사력과 필력이 돋보였다. 서로다른 환경 속 각각 성장하는 인물들, 그리고 그들의 특징과 관계성에 집중하며 읽었다. 현실고발이라고 느껴질 만큼 생동감이 넘치는 전개는 좋았으나, 작품의 마무리는 많이 허술하다고 느껴졌다. 훌륭했던 빌드업만큼, 전달하는 메세지도 강렬했다면 어땠을까.

**[무진기행]**

개인적으로 쿨타임이 돌때마다 읽고 싶어지는 짧은 단편. 무진기행은 원체 유명하고, 수능에도 나올정도로 그 내용에 대한 분석은 충분히 이루어져있다. 단, 내가 무진기행을 좋아하는 이유는 읽을 때마다 '무진'의 안개가 눈앞에 펼쳐지는 것처럼 느껴지기 때문이다. 그 특유의 감각과 감성이 좋다.


본래는 마지막으로 읽고 있던 '괴테는 모든 것을 말했다'까지 완독하고 작성하고 싶었으나... 본업에 집중해야할 시간이 필요해 하반기로 미룸!
