---
title: "Letter_2602"
description: "Documentation of a letter from past self"
date: "2026-05-16"

toc: false
categories:
  - Anecdotes
---

To. 5월의 수브로

안녕, 이걸 읽고 있을 시점이면 정말 많은 우여곡절, 산전수전을 지나, 현업 배치를 눈 앞에 두고 있는 시기일 것 같아. 목표한 것들, 이루고 싶었던 것들은 어떻게 됐을지 궁금해. 생각보다 많이 이루었을 수도, 생각 만큼만 성취했을 수도, 기대에 못 미치게 완주했을지도 모르겠다. 많이 뿌듯할수도, 아니면 또 스스로에게 실망하고 있을 수도 있겠지. 하지만 중요한 순간에 항상 결정을 내려왔던 너의 가치관대로 최선을 다했다면 얻어갈 것은 모두 얻었을 것이라 생각해.

그 과정에서 얻은 것은 강한 pivot점으로, 아직 성취하지 못한 것들은 여백의 미로 여길 수 있었으면 좋겠다. 모든 것은 점을 이어가는 과정이니까. 지금 가진 점들을 이어 그려갈 그림도, 앞으로 채워나갈 여백도 넓게 바라보고, 도전할 수 있는 마음을 잃지 않았으면 해.

지금의 나보다도 더 많이 느끼고 있겠지만, 거대한 조직 속에서 '나'라는 한 사람에게 주어지는 기회와 권한은 꽤 한정적일 것이라고 생각해. 그 다소 폭력적으로 다가올 수 있는 현실 앞에서 무너지지 말고, 스스로 단단한 fundamental을 다지기 위한 노력에만 눈이 멀기를 바랄게. 기회는 어떤 형태로는 올 것이고, 그걸 잡을 준비는 되어있어야 하니까 말이야.

여기부터는 5월 후의 내가, 또다시 3년, 5년 후의 나에게 어떤 말을 해주고 싶어할지 궁금해. 내가 쓴 편지가 완전히 뜬 구름 잡는 소리처럼 느껴질 가능성이 크겠지. 그래도 한번쯤 읽어보면서 과거의 패기를 느끼는 것 만으로도 하나의 자극이 된다면, 그것 나름의 의미가 있지 않을까? 구체적인 조언이나 도움이 되어줄수는 없을 것 같아 미안해.

연애, 일, 가족, 투자 등 정말 많은 신경 쓸 일들과 늘어가는 책임 앞에서 짓눌리지는 않을까 걱정되는 마음도 커. 마음의 여유를 찾기 위한 운동, 스포츠, 친구와의 시간들을 그래도 많이 할애해줬으면 좋겠어. 열심히 하는 것 만큼 중요한 것이 지구력이니까. 마지막으로, 건강도 열심히 챙기라고 이제는 부모님이 아니라 내가 스스로에게 다시 말해주고파. 이젠 본격적으로 어른이니까! 일도, 건강도, 마음도 모두 고르게 성숙한 사람이 되기 위해 항상 열심히 하길. 화이팅!

From. 2026.02.06 16:00의 나
