---
title: "M&A Studies - 2"
description: "Covers Deal Proposals to Deal Structuring"
date: "2026-02-23"
toc: false
categories:
  - Study
---

## 거래의 시작

앞선 포스팅에서 M&A 거래의 일반론적 Process를 다음과 같이 정리한 바 있다.

  + M&A 동기, 목표 및 전략의 구조화
  + 타깃 선정
  + `거래 의향 확인`
  + 비밀유지확약서(CA; Confidential Agreement) 체결
  + 예비적 제안 (LOI; Letter of Intent)
  + 텀시트 체결 (Termsheet, MOU)
  + 실사 (DD; Due Diligence)
  + 본계약 체결 및 클로징 (DA; Definitive Agreement)

이번 포스팅은 거래 의향 확인부터 거래 방식의 선택, Deal Structuring까지 다뤄보고자 한다.

## 거래 의향의 확인

해당 M&A 딜이 소싱된 방식에 따라 대상 기업의 거래 의향이 이미 확인됐을 수도, 불명일 때도 있다. M&A 중개사를 통해 딜을 소싱한 경우에는 대부분의 경우 이미 대상 기업의 거래 의향이 확인된 경우일 것이다. 이 단계는 주로 M&A 투자자가 직접 소싱하거나, 산업 분석 중 발견한 기업에 접근하는 경우에 해당되는 내용이다.

#### To Whom

M&A 거래의 논의는 대상기업이 *아니라,* 반드시 기업의 경영권 지분을 가진 Owner에게 접촉하는 것으로 시작돼야 한다. 결국 M&A 대상이 될 수 있는지 아닌지는 오너의 직접적인 의향만이 유효하다. 고로, 전문경영인, 내부 임원 등의 생각과는 별개로 Owner에게 직접 접촉하여 의사를 확인해야하며, 불가피하다면 Owner와 직접적인 커뮤니케이션이 가능한 사람을 통해 해야한다.

#### Who will

M&A 첫 접촉의 담당자는 반드시 경험이 많은 자문사, 혹은 전담부서의 책임자가 진행해야한다. 커뮤니케이션 상의 미숙함으로 인해 의사를 파악하기도 못하고 미팅이 끝나버리거나, 감정이 상하는 경우가 많기 때문이다. 특히 언론 등에 민감한 대기업의 경우에는 익명으로 자문사를 통해 접근하는 경우가 빈번하다.

#### How

M&A 거래는 대부분 대면 미팅으로 통해 전달되며, 명확한 커뮤니케이션을 통해 서신을 통해 의향을 드러내기도 한다. 핵심은 `신뢰감`을 주는 것이다. 인수 목적의 타당성, 시너지, 평판, 자금조달능력 등에서 진정성과 적합성의 인상을 심어주는 것으로 Private Deal의 기회를 얻을 수도 있다.

## 거래 방식의 선택

기업의 경영권을 획득하는 거래는 일반적으로 경영권 지분을 인수하는 방식으로 진행되지만, 인수 목적, 기업의 우발채무 여부, 세금의 최소화 등의 관점에서 영업양수도 거래 등 다른 방식을 고려할 수 있다.

| 구조 | **지분거래** (Share Deal) | **영업양수도 거래** (Asset Deal) |
|:---|:---|:---|
| **내용** | 주식 매매거래를 통해 경영권을 양수도 | 사업 단위로 특정 사업을 양수도 |
| **특징** | 거래대금은 대상기업의 주주에 귀속함<br>지분거래를 통해 대상기업의 자산, 부채, 권리 및 의무관계(고용포함)가 모두 자동 승계됨<br>상대적으로 절차가 간편함<br>매수자가 지급하는 프리미엄에 대해 세무상 비용으로 인정되지 않음 | 거래대금은 주주가 아닌 대상기업에 귀속함<br>거래 대상사업으로 규정한 사업과 관련된 자산, 부채, 권리 및 의무가 승계됨<br>포괄적으로 대상사업이 이전되더라도 개별적으로 권리, 의무관계를 이전하는 절차가 필요하며, 거래 절차 및 일정이 상대적으로 복잡함<br>매수자가 지급하는 프리미엄이 세무상 영업권으로 인정되는 경우 비용처리 가능함 |

이 두가지의 핵심 차이점은 지분거래는 주식을 거래대상으로 하지만, 영업양수도 거래는 특정한 사업과 관련 자산을 거래대상으로 한다는 점이다. 거래 대상이 다른 만큼, 절차나 재무적인 측면에서 차이가 존재한다. 가장 큰 차이는 매매대금이 주주에게 바로 귀속되는지 VS 대상기업에 귀속되는지다. 영업양수도 거래의 경우, 주주가 거래대금을 획득하기 위해 추가적으로 배당 등의 과정을 거쳐야하고 여기서 추가적인 세금 부담이 발생한다. 즉, 매도인은 특별한 상황이 아니라면 대부분 지분거래를 선호한다.

그럼에도 영업양수도 거래를 선호하는 상황은 `1. 투자자가 일부 사업에만 관심이 있을 때`, `2. 대상기업의 우발채무 리스크가 있을 때`, `3. 영업권의 비용처리를 통해 세무적 이점을 고려할 때`이다.

#### 1. 투자자가 일부 사업에만 관심이 있을 때

대상기업 내에 성격이 다른 둘 이상의 이종사업이 경영될 때, 투자자의 입장에서는 일부 사업만 인수가치가 있다고 평가할 수 있다. 이 경우, 투자자는 통째로 인수한 뒤 이후 관심 없는 사업부를 매각하는 방안과 애초에 영업양수도 거래를 하는 방안 중에 선택해야 한다. 이 선택은 대부분의 경우 투자자와 매도자간의 관계에 따라 결정된다. 매도인의 협상력이 크거나 관심없는 사업부문이 작을수록 전자를 선택해야 할 것이다. 반면, 매수인의 협상력이 크거나 관심없는 사업부문이 클수록 후자를 선택하게 될 것이다.

#### 2. 대상기업의 우발채무 리스크가 있을 때

대상기업에 *세금, 소송 등 우발채무 리스크가 존재하는 경우*, 지분거래를 통해 모든 의무관계를 자동 승계하는 것이 투자자의 입장에서 부담스러울 수 있다. 물론 주식매매 계약(SPA)에서 손실보전/손해배상 조항을 통해 헤지할 수도 있지만, 리스크가 과도하게 크거나 매도인의 신용도가 낮을 경우 이는 적합하지 않다. 단, 영업양수도 거래 역시 모든 우발채무 리스크에서 자유로워지는 것은 아니므로, 관련 법률관계를 면밀히 검토해야 한다. 

#### 3. 영업권의 비용처리를 통해 세무적 이점을 고려할 때

영업양수도 거래의 경우, 거래대금에 포함된 프리미엄을 영업권으로 인식해 세무상 비용으로 처리할 수 있다. *투자자가 비상장기업*으로 회계적 이익 변동보다 세무부담을 더 중요하게 고려해야 하는 상황이라면 이를 적극적으로 고려할 필요가 있다.

## 거래구조의 수립 (Deal Structuring)

거래구조 수립을 통상 딜 스트럭쳐링(Deal Structuring)이라고 표현한다. 딜 스트럭쳐링은 거래가격, 거래대상 지분율, 대금 지급 시기 등 M&A의 전체적인 조건을 구성하는 것으로 거래를 설계하는 작업이라고 말할 수 있다. 다양한 조건들이 포함되게 되며, 각 조건은 서로에게 영향을 주므로, 각 거래조건을 적절히 조합하는 작업이 중요해지는 것이다.

#### 딜 스트럭쳐링 고려사항

거래구조 수립에 있어 원론적으로 고려해야하는 사항들에 대해서 정리해보자.

##### 1. 시너지 수혜자는 누구인가

거래를 통해 시너지의 수혜가 투자자, 대상기업 중 누가 더 큰지 파악해야 한다.

##### 2. 시장에 어떤 인상을 줄 것인가

M&A 거래 공표는 주식시장에서 주가, 신용등급 등 기업의 자금조달 시장에도 영향을 미친다.

##### 3. 재무적 효과

거래구조에 따라 재무제표에 미치는 영향이 달라질 수 있으므로, financial ramification에 대해 사전에 파악해놓고 있어야 한다.

##### 4. 지배구조 변화 가능성

매수 주체를 누구로 정하느냐에 따라 거래 이후 전체적인 기업 지배구조가 달라질 수 있으며, 이는 기업의 회계, 재무 및 세금 등 전반적인 사항에 영향을 준다.

##### 5. 세무적으로 유리한 구조인가

거래 주체, 지급 방법, 지급 시기 등에 따라 거래 당사자의 세금 효과가 달라진다. 

##### 6. 리스크 최소화 구조인가

우발채무 등의 큰 리스크 존재하는 경우 이를 단절시킬 수 있는 구조인지 충분히 검토해야 한다. 분할 후 지분거래, 영업양수도, 자산양수도 거래 등을 고려할 수 있다.

#### 거래조건의 조합

거래조건은 초기부터 검토를 시작해, 진행 과정에서 계속적으로 수정해 나가야 한다. 실사의 결과, 협상 과정에서의 조율 등으로 인해 거래구조는 달라지기도 한다.

##### 1. 거래 주체

거래의 당사자를 정하는 것으로, 지주회사가 인수할지 사업회사가 인수할지 정해야 한다. 거래 주체가 누구인지에 따라 기업의 전체적인 지배구조에 영향을 미치며, 재무보고 관련 사항 및 세금 효과 등이 달라지므로 투자자 입장에서는 거래 주체별 비교 검토를 수행해야한다.

##### 2. 거래 방식

앞서 논의한 내용대로 지분거래, 영업양수도 등의 방식으로 비교 고려해야한다. 추가로, 대상기업에 자금이 필요할 것으로 예상되면 구주거래 방식 외에 유상증자 방식을 도입하기도 한다.

##### 3. 거래 지분율

핵심은 실질적인 경영권 행사가 가능한 지분율을 차지하는 것이다. 상황에 따라 50% 이하가 될수도, 100%에 가까울 수도 있다. 구체적인 지분율은 `M&A 효익의 주체가 누구`인지, 매도인이 소수주주로 남는것이 필요한지 등에 따라 고려해서 결정해야 한다.

예를 들어, **시너지 효과가 대상기업에 주로 발생한다면 인수자의 입장에서 거래 지분율을 높이는 것이 좋으며, 반대의 경우에는 최소한의 지분율로 거래하는 것이 투자 대비 효과를 극대화할 수 있을 것이다. 또한, 시너지 발생까지 시차가 예상되는 경우, 지분율을 점진적으로 높이는 방법도 고려할 수 있다.**

##### 4. 거래 가격

가장 기본적이자 중요한 조건이다. 거래가격은 나머지 거래조건의 Trade-Off로 작용한다. 즉, 높은 거래가격은 타 조건들을 유리하게 설계할 수 있게 해주며, 반대로 타 조건들을 매도인에게 유리하게 설계해 준다면 거래가격에 대한 조정을 협의해 볼 여지가 생기는 것이다.

##### 5. 거래대금 지급 방법

대금은 대부분 현금으로 지급하는 것이 일반적이지만, 주식 등 다른 지불 수단이 이용되기도 한다. 주식 스와프 등의 방법이 활용되는 경우도 있다. 

##### 6. 지급 시기

가장 중요한 조건 중 하나로, 통상 거래대급 지급 방법과 함께 고려된다. 거래가격과 마찬가지로, 지급 시기는 한쪽에 혜택을, 반대쪽에 기회손실을 주므로 나머지 거래조건의 Trade-Off로 작용한다,

##### 7. 종업원 고용승계

거래조건에 고용승계 사항이 포함되는 경우도 있다. 매도인의 요청에 따라, 혹은 종업원/노조의 불안 및 동요 가능성의 최소화를 위해 명시하기도 한다.

## 마무리

이번 포스팅은 M&A의 Deal Structuring에 대해 다루는 것으로 마무리다. 다음 포스팅은 M&A 예비적 제안 부터 Valuation & DD 까지 다뤄볼 예정!