---
title: "Passerby"
description: "Anecdote"
date: "2026-02-22"

toc: false
categories:
  - Anecdotes
---

대학교 초년생 시절, 우연히 알게 된 선배가 있었다. 그 계기는 입학한 직후, 무작정 기타를 배워보겠다고 학교의 클래식 기타 동아리에 입부한 것. 이 동아리의 특이점은 기수마다 단체 연주 공연을 준비해서 올리는 것, 그리고 반기마다 설악산, 지리산 등 유명한 산에 OB와 YB 함께 팀을 짜서 오른다는 것이었다.

이 선배는 당시 겨울 설악산을 오르면서 같은 팀으로 배정된 선배였다. 이미 상당히 시간이 지나 기억나는 것은 많지 않지만, 선배가 어떤 사람이었는지는 아직도 명확할 정도로 인상적인 사람이었다. 산을 오를 때는 누구보다도 든든하고, 함께 이야기 나눌 때는 특유의 텐션으로 주변사람을 즐겁게 해주고, 무언가 실수했을 때는 배려심을 보여주는 사람이었다. 완전히 극내향인이었던 내가, 등산이 끝난 술자리에서 그렇게 즐겁게 이야기 나누고 놀 수 있었던 것 역시 그 때문이었다. 사람이 좋았기 때문일까, 그는 심지어 이 여행을 통해 사랑도 싹틔우고 떠났던 것으로 기억한다.

하지만 대부분의 스쳐 지나가는 인연이 그렇듯이 나는 곧 입대했고, 그 이후에는 코로나가 터지는 바람에 동아리 활동에서 자연스레 멀어졌다. 품을 들여 연락을 이어가거나, 동아리 활동에 다시 참여할 수도 있었겠지만, 당장의 학업, 취업 고민, 연애에 치여 그렇지는 못했다. 그렇게 그는 내가 잊은 사람 중 하나가 됐다.

1년 반쯤 전일까, 갑자기 그에게서 카톡이 왔다. 한창 인턴 중, 밤을 새워가며 일을 하던 시절이었다. 예상치 못한 그의 이름을 보고 반가운 마음에 열어본 카톡은 야속하게도 그의 누나가 보내온 것이었다. 그의 부고를 전달하기 위한 연락이었다. 당연히 그 이유도, 경황도 물어볼 수 없었다. 연이 끊긴 지 오랜 사람인 나에게 그런 것을 물을 권리가 있었다고 생각하지 않았다. 그 와중에 순간 마음이 철렁했던 내가 참 위선적이고, 한편으로는 염치없다는 생각이 들었을 뿐이었다. 그 와중에 그의 카톡 스토리에 있는 결혼을 암시하는 사진들은 내 부끄러운 상상만을 키워, 가상의 비극을 키워갈 뿐이었다.

야속하게도 나는 다시 바쁜 일상, 여유 없는 취준, 복잡 피곤한 일상사 속에서 다시금 선배를 잊어갔다. 그러다가 오늘, 갑자기 카톡 메인의 프로필 업데이트에 그의 이름이 떴다. 낯선 사람의 사진이 올라와 있었다. “선배의 전화번호가 다른 사람에게 넘어갔구나.”라는 사실을 곧 깨달았다. 다시 한번 기분이 가라앉았다. 이번에는 달랐던 것은 내가 느끼는 감정을 무엇이라고 이름 붙여야 할지 감이 오지 않는다는 것 정도랄까.

올해 달력에는 선배의 기일을 기록해 두었다. 많은 것이 안정되기 시작한 지금, 한번 찾아뵙기 위해서다. 멋대로 잊어놓고, 멋대로 찔리고, 그리고 멋대로 끝맺음을 하기 위해서일지도 모르지만. 이기적이라는 생각도 들지만, 참 못 배기겠다.
